server {
    listen 80;
    server_name localhost;

    root /var/www/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

     # Для PHP (если нужно) - раскомментируйте:
     location ~ \.php$ {
#         include snippets/fastcgi-php.conf;
         fastcgi_pass apache-container:9000;
     }

    # Для статических файлов
    location ~* \.(jpg|png|mp3)$ {
        root /var/www/html;
        access_log off;
        expires 30d;
    }
}
